import { streamXML } from "../smol-xml.ts"

const xml = `
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="37059" uniqueCount="4493"><si><t xml:space="preserve">Couche</t></si><si><t xml:space="preserve">Type</t></si><si><t xml:space="preserve">Marqueur</t></si><si><t xml:space="preserve">Cluster</t></si><si><t xml:space="preserve">Ordonnancement</t></si><si><t xml:space="preserve">UGA</t></si><si><t xml:space="preserve">Brick</t></si><si><t xml:space="preserve">-</t></si><si><t xml:space="preserve">Secteur</t></si><si><t xml:space="preserve">Territoire</t></si><si><t xml:space="preserve">Région</t></si><si><t xml:space="preserve">Zone</t></si><si><t xml:space="preserve">PdS</t></si><si><t xml:space="preserve">Point</t></si><si><t xml:space="preserve">liste de marqueurs CEY</t></si><si><t xml:space="preserve">Comptes</t></si><si><t xml:space="preserve">Scénario</t></si><si><t xml:space="preserve">Niveau</t></si><si><r><rPr><b val="true"/><sz val="11"/><color rgb="FF220E55"/><rFont val="Plus Jakarta Sans"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve">Data </t></r><r><rPr><b val="true"/><i val="true"/><sz val="11"/><color rgb="FF220E55"/><rFont val="Plus Jakarta Sans"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve">doing </t></r><r><rPr><i val="true"/><sz val="11"/><color rgb="FF220E55"/><rFont val="Plus Jakarta Sans"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve">stuff</t></r></si><si><t xml:space="preserve">Max</t></si><si><t xml:space="preserve">Max included</t></si><si><t xml:space="preserve">Légende Tranche</t></si><si><t xml:space="preserve">Couleur</t></si><si><t xml:space="preserve">Ventes Produit</t></si><si><t xml:space="preserve">1-1000</t></si><si><t xml:space="preserve">1001-2200</t></si><si><t xml:space="preserve">#Etab</t></si><si><t xml:space="preserve">0-30</t></si><si><t xml:space="preserve">31-39</t></si><si><t xml:space="preserve">40-100</t></si><si><t xml:space="preserve">Sc1/Zone</t></si><si><t xml:space="preserve">Sc1/Région</t></si><si><t xml:space="preserve">Sc2/Zone</t></si><si><t xml:space="preserve">Sc2/Région</t></si><si><t xml:space="preserve">01BEL</t></si><si><t xml:space="preserve">B</t></si><si><t xml:space="preserve">R3</t></si><si><t xml:space="preserve">R3S01</t></si><si><t xml:space="preserve">S</t></si><si><t xml:space="preserve">RA/Bourgogne/FC</t></si><si><t xml:space="preserve">01BOU</t></si><si><t xml:space="preserve">R3S07</t></si><si><t xml:space="preserve">01GEX</t></si><si><t xml:space="preserve">01MIR</t></si><si><t xml:space="preserve">01NAN</t></si><si><t xml:space="preserve">01TRE</t></si><si><t xml:space="preserve">02CHA</t></si><si><t xml:space="preserve">A</t></si>
</sst>`

streamXML("si", xml, (node) => {
  console.log(node.textContent)
})
